name: Get Build Logs

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

jobs:
  get-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Download Logs
      uses: actions/download-artifact@v2
      with:
        name: build-logs
        path: logs  # Change this to the desired directory to store logs locally
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
